"""changing password field name

Revision ID: 19ee05769656
Revises: b2da639f0491
Create Date: 2025-02-13 10:12:45.322275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ee05769656'
down_revision: Union[str, None] = 'b2da639f0491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=False))
    op.drop_column('users', 'passworrd')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('passworrd', sa.VARCHAR(), nullable=False))
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
