"""add field active and password

Revision ID: 847af78310a6
Revises: c74bd65fd56a
Create Date: 2025-02-12 09:00:31.113389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '847af78310a6'
down_revision: Union[str, None] = 'c74bd65fd56a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('passworrd', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'passworrd')
    op.drop_column('users', 'active')
    # ### end Alembic commands ###
