"""changing active field name

Revision ID: b2da639f0491
Revises: 847af78310a6
Create Date: 2025-02-13 10:04:11.749647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2da639f0491'
down_revision: Union[str, None] = '847af78310a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('users', 'active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('active', sa.BOOLEAN(), nullable=False))
    op.drop_column('users', 'is_active')
    # ### end Alembic commands ###
